- name: services directory
  ansible.builtin.file:
    path: /root/services/
    state: directory
    mode: "700"
  become: yes

- name: copy
  ansible.builtin.copy:
    src: portainer
    dest: /root/services/
    owner: root
    group: root
    mode: "700"
  become: yes

- name: run portainer
  ansible.builtin.shell: "cd /root/services/portainer && docker compose down && docker compose up -d"
