- name: install packages
  community.general.pacman:
    update_cache: yes
    name: wireguard-tools
    state: present

- name: wg-javips
  ansible.builtin.copy:
    src: files/wg-javips.conf
    dest: /etc/wireguard/wg-javips.conf
    owner: root
    group: root
    mode: "600"
  notify: restart wg-javips

- name: ensure wg-quick@wg-javips.service is started and enabled at boot
  ansible.builtin.systemd:
    name: wg-quick@wg-javips.service
    state: started
    enabled: yes
