- name: services directory
  ansible.builtin.file:
    path: /root/services/
    state: directory
    mode: "700"
  become: yes

- name: copy
  ansible.builtin.copy:
    src: nextjs-app
    dest: /root/services/
    owner: root
    group: root
    mode: "700"
  become: yes

- name: run nextjs-app
  ansible.builtin.shell: "cd /root/services/nextjs-app && docker compose down && docker compose up -d"
