- name: install docker
  ansible.builtin.apt:
    update_cache: yes
    name: docker
    state: present
  notify: restart docker
  become: yes

- name: /etc/docker directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "755"
  become: yes

- name: daemon.json
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "644"
  notify: restart docker
  become: yes

- name: ensure Docker is started and enabled at boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: install docker-compose
  ansible.builtin.apt:
    update_cache: yes
    name: docker-compose
    state: present
  notify: restart docker
  become: yes
