- name: install cron on Ubuntu
  ansible.builtin.apt:
    update_cache: yes
    name:
      - cron # cron implementation
    state: present
  become: yes

- name: ensure cronie is started and enabled at boot
  ansible.builtin.systemd:
    name: cronie
    state: started
    enabled: yes
  become: yes
  when: ansible_facts['os_family'] == "Archlinux"
