- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Certbot and Cloudflare plugin via pip
  ansible.builtin.pip:
    name:
      - certbot
      - certbot-dns-cloudflare
    state: present
    executable: pip3
  become: yes

- name: certbot
  ansible.builtin.copy:
    src: certbot
    dest: /root/
    owner: root
    group: root
    mode: "700"
  become: yes

### You can skip these two.
### `certbot.service` and `certbot.timer` now come installed with the `certbot` package.
- name: service
  ansible.builtin.copy:
    src: files/certbot.service
    dest: /etc/systemd/system/certbot.service
    owner: root
    group: root
    mode: "644"
  become: yes

- name: timer
  ansible.builtin.copy:
    src: files/certbot.timer
    dest: /etc/systemd/system/certbot.timer
    owner: root
    group: root
    mode: "644"
  become: yes

### You still need to start and enable `certbot.timer` though!
- name: ensure certbot.timer is started and enabled at boot
  ansible.builtin.systemd:
    name: certbot.timer
    state: started
    enabled: yes
  become: yes

- name: run get-certs
  command: "/root/certbot/get-certs.sh"
