- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  become: yes

- name: restart netfilter-persistent
  ansible.builtin.systemd:
    name: netfilter-persistent
    state: restarted
  become: yes

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: yes
