# Si no queremos que aparezca en las HTTP routes dejar este archivo vacio!
http:
  routers:
    portainer:
      rule: Host(`portainer.javips.digital`)
      tls:
        certresolver: letsencrypt
      service: portainer
      entryPoints:
        - https
      middlewares:
        - portainer-allowlist

  middlewares:
    portainer-allowlist:
      ipallowlist:
        sourceRange:
          - ${ip_allowlist}

  services:
    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000
