- name: Ensure the /root/services directory exists
  ansible.builtin.file:
    path: /root/services/
    state: directory
    owner: root
    group: root
    mode: "0700"
  become: yes

- name: Copy the hello-world-fake directory to /root/services
  ansible.builtin.copy:
    src: hello-world-fake
    dest: /root/services/
    owner: root
    group: root
    mode: "700"
  become: yes

- name: run hello-world-fake
  ansible.builtin.shell: "cd /root/services/hello-world-fake && docker compose down && docker compose up -d"
  become: yes
